# Матрицы и векторы

In [1]:
import numpy as np

## 1. Скалярное умножение векторов

$$(a, b) = \sum a_i b_i$$

In [2]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

In [3]:
a

array([1, 2, 3])

In [4]:
np.dot(a, b)

26

Реализуем скалярное произведение средствами Python

In [5]:
sum([x * y for x, y in zip(a, b)])

26

Примеры:

Следующие два примера – ортогональные векторы

In [6]:
np.dot([0, 1], [1, 0])

0

In [7]:
np.dot([3, 1, 2], [-1, 1, 1])

0

In [8]:
np.dot([1, 2, 3], [2, 4, 6])

28

In [9]:
np.dot([-10, -1], [1, 1])

-11

## 2. Длина вектора через скалярное произведение

$$\lvert a\lvert= \sqrt{(a, a)}$$

In [10]:
a

array([1, 2, 3])

In [11]:
np.sqrt(np.dot(a, a))

3.7416573867739413

In [12]:
np.linalg.norm(a)

3.7416573867739413

In [13]:
np.linalg.norm([0, 1])

1.0

In [14]:
np.linalg.norm([3, 4])

5.0

In [15]:
np.linalg.norm([-1, -1])

1.4142135623730951

In [16]:
np.sqrt(2)

1.4142135623730951

## 3. Сложение матриц и умножение на число

Матрицы складываются поэлементно. При умножении на число все элементы матрицы умножаются на это число.

In [17]:
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 2))

In [18]:
a, b

(array([[7, 0],
        [1, 8]]), array([[7, 9],
        [1, 0]]))

In [19]:
a + b

array([[14,  9],
       [ 2,  8]])

In [20]:
a

array([[7, 0],
       [1, 8]])

In [21]:
a * 2

array([[14,  0],
       [ 2, 16]])

$I$ или $E$ – единичная матрица

In [22]:
eye_matrix = np.eye(3)

In [23]:
eye_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
eye_matrix * 5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

## 4. Умножение матриц

Для умножения нужно, чтобы **средние** размерности совпадали: умножить можно только $n*k$ на $k*m$  
Под средними размерностями подразумеваются те размерности, которые находятся посередине при записи размерностей двух матриц. В примере выше это *k*

In [25]:
a

array([[7, 0],
       [1, 8]])

In [26]:
b

array([[7, 9],
       [1, 0]])

Проверим на первой строке первой матрицы и на первом столбце второй матрицы  
**1, 1** – первая строка первой матрицы, первый столбец второй матрицы  
([5 7], [1 2]) – скалярное произведение этих векторов

5\*1 + 7\*2 = 19


**1, 2**  
([5, 7], [2, 6])  
5\*2 + 7\*6 = 52

In [27]:
np.dot(a, b)

array([[49, 63],
       [15,  9]])

In [28]:
a @ b

array([[49, 63],
       [15,  9]])

In [29]:
np.matmul(a, b)

array([[49, 63],
       [15,  9]])

dot и matmul работают одинаково для 2д матриц, но matmul не позволяет перемножать скаляры и работает по-другому для измерений 3+

In [30]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (5, 3))

In [31]:
a, b

(array([[1, 1, 4, 3, 4],
        [4, 3, 0, 1, 2]]), array([[4, 4, 0],
        [2, 2, 2],
        [2, 0, 3],
        [4, 1, 0],
        [2, 1, 3]]))

In [32]:
result = np.matmul(a, b)

In [33]:
result

array([[34, 13, 26],
       [30, 25, 12]])

Размерность:

In [34]:
result.shape

(2, 3)

## 5. Связь со скалярным произведением

In [35]:
result

array([[34, 13, 26],
       [30, 25, 12]])

In [36]:
# i = 1, j = 2
result[1, 2]

12

In [37]:
a, b

(array([[1, 1, 4, 3, 4],
        [4, 3, 0, 1, 2]]), array([[4, 4, 0],
        [2, 2, 2],
        [2, 0, 3],
        [4, 1, 0],
        [2, 1, 3]]))

In [38]:
np.dot(a[1,:], b[:, 2])

12

В результате умножения матриц в элементе с индексом (i, j) лежит скалярное произведение i-й строки первой матрицы на j-й столбец второй матрицы

## 6. Умножение матриц некоммутативно

Если средние размерности не совпадают, то умножить вообще нельзя:

Перемножение скаляров коммутативно:

In [39]:
2 * 3 == 3 * 2

True

In [40]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (4, 3))
# np.dot(a, b)

Средние размерности совпадают, но размерности матриц разные:

In [41]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (5, 3))

In [42]:
# np.dot(a, b)

In [43]:
# np.dot(b, a)

Размерности матриц одинаковые:

In [44]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))

In [45]:
a, b

(array([[2, 2],
        [4, 4]]), array([[4, 0],
        [0, 4]]))

In [46]:
np.dot(a, b)

array([[ 8,  8],
       [16, 16]])

In [47]:
np.dot(b, a)

array([[ 8,  8],
       [16, 16]])

## 7. Умножение матриц ассоциативно

$$(AxB)xC==Ax(BxC)$$

In [48]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))
c = np.random.randint(0, 5, (2, 2))

In [49]:
np.dot(np.dot(a, b), c) == np.dot(a, np.dot(b, c))

array([[ True,  True],
       [ True,  True]])

## 8. Вычисление определителей

In [50]:
a = np.random.randint(0, 5, (2, 2))
a

array([[3, 4],
       [0, 3]])

In [51]:
det = a[0, 0]*a[1, 1] - a[1, 0]*a[0, 1]
det

9

In [52]:
np.linalg.det(a)

9.000000000000002

Примеры:

In [53]:
# Вторая строка равна первой, умноженной на 2 – строки линейно зависимы
np.linalg.det(np.array([[1, 2], [2, 4]]))

0.0

In [54]:
# Диагональная матрица, поэтому произведение элементов на диагонали
np.linalg.det(np.array([[2, 0], [0, 3]]))

6.0

In [55]:
np.array([[2, 2], [0, 3]])

array([[2, 2],
       [0, 3]])

In [56]:
# Верхнетреугольная матрица, поэтому произведение элементов на диагонали
np.linalg.det(np.array([[2, 2], [0, 3]]))

6.0

## 9. Определитель произведения матриц

$$det(A*B)=det(A)*det(B)$$

In [57]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))

In [58]:
a, b

(array([[3, 1],
        [1, 0]]), array([[2, 0],
        [4, 2]]))

In [59]:
np.linalg.det(np.dot(a, b))

-4.000000000000001

In [60]:
np.linalg.det(a) * np.linalg.det(b)

-4.0

## 10. Единичная и обратная матрицы

Вычисления работают для квадратных матриц. Если определитель равен 0, обратной матрицы не существует.

$$A \cdot A^{-1} = E$$

In [61]:
a

array([[3, 1],
       [1, 0]])

In [62]:
np.linalg.det(a)

-1.0

In [63]:
np.linalg.inv(a)

array([[ 0.,  1.],
       [ 1., -3.]])

In [64]:
np.dot(np.linalg.inv(a), a)

array([[1., 0.],
       [0., 1.]])

In [65]:
np.linalg.det(np.array([[1, 2], [2, 4]]))

0.0

In [66]:
# np.linalg.inv(np.array([[1, 2], [2, 4]]))
# LinAlgError: Singular matrix

## 11. Коммутативность прямой и обратной матрицы

$$A \cdot A^{-1} = A^{-1} \cdot A  = E$$

In [67]:
a

array([[3, 1],
       [1, 0]])

In [68]:
inv_a = np.linalg.inv(a)

In [69]:
inv_a

array([[ 0.,  1.],
       [ 1., -3.]])

In [70]:
np.dot(a, inv_a).astype(int)

array([[1, 0],
       [0, 1]])

In [71]:
np.dot(inv_a, a)

array([[1., 0.],
       [0., 1.]])

## 12. Поиск обратной матрицы методом Крамера

In [72]:
def matrix_inverse(m):
    # только 2D
    determinant = np.linalg.det(m)
    return [[m[1][1]/determinant, -1*m[0][1]/determinant],
            [-1*m[1][0]/determinant, m[0][0]/determinant]]

In [73]:
a

array([[3, 1],
       [1, 0]])

In [74]:
np.linalg.inv(a)

array([[ 0.,  1.],
       [ 1., -3.]])

In [75]:
np.array(matrix_inverse(a))

array([[-0.,  1.],
       [ 1., -3.]])

## 13. Тензорное произведение векторов

Как работает:

$$a = 
\begin{pmatrix}
a_1 & a_2
\end{pmatrix}$$

$$b = 
\begin{pmatrix}
b_1 & b_2
\end{pmatrix}$$

$$
c = a \space tensordot \space b = 
\begin{pmatrix}
a_1 \cdot [b_1, b_2] \\
a_2 \cdot [b_1, b_2] \\
\end{pmatrix}
$$

In [76]:
a = np.random.randint(0, 10, size=2)
b = np.random.randint(0, 10, size=2)

In [77]:
a, b

(array([8, 5]), array([2, 2]))

In [78]:
np.tensordot(a, b, axes=0)

array([[16, 16],
       [10, 10]])

Ссылка: https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

Посмотрим как делать slice в тензоре

In [79]:
test = np.random.randint(0, 10, size=(2, 2, 3))

In [80]:
test

array([[[8, 3, 9],
        [0, 9, 9]],

       [[5, 7, 8],
        [4, 7, 9]]])

In [81]:
test[:, :, 1]

array([[3, 9],
       [7, 7]])

In [1]:
import numpy as np
import pandas as pd

In [7]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])


In [3]:
share_living_space = apartment[1]/apartment[0]

In [4]:
share_living_space

0.5277310924369748

In [8]:
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)

apartment.ndim

1

In [9]:
len(apartment)

5

In [11]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

t.mean()

21.25

In [13]:
np.array([120, 150, 90]) + np.array([130, 130, 130]) + np.array([2,3,2.5])*72

array([394., 496., 400.])

In [14]:
-200*np.array([3,4,5,9]) + 400*np.array([1, 5, 3, 6])

array([-200, 1200,  200,  600])

In [15]:
a = np.array([4,6,1])

np.sqrt(np.dot(a, a))

7.280109889280518

In [2]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [5]:
Hut_Paradise_DF.loc[4]

1.Rent              40
2.Area              33
3.Rooms              1
4.Floor              6
5.Demo two weeks    20
6.Liv.Area          16
Name: 4, dtype: int64

In [6]:
Hut_Paradise_DF.loc[4].values

array([40, 33,  1,  6, 20, 16])

In [8]:
Hut_Paradise_DF['4.Floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [10]:
Hut_Paradise_DF['4.Floor'][2]

10

In [11]:
Hut_Paradise_DF.shape

(9, 6)

In [13]:
(Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [15]:
(Hut_Paradise_DF['1.Rent'] * 0.4).values

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [16]:
min_demo = np.array([10,20,30,15,5,40,20,8,20])

Hut_Paradise_DF['5.Demo two weeks'] @ min_demo

1348

In [17]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [20]:
av_bw = 2*v + -3*w
av_bw

array([-3, 14,  3,  4,  2])

In [21]:
u @ av_bw

0

In [34]:
for vec in u, v, w:
  print(np.round(vec/np.linalg.norm(vec), 3))

[0.866 0.    0.289 0.289 0.289]
[ 0.     0.333  0.     0.667 -0.667]
[ 0.213 -0.853 -0.213  0.    -0.426]


In [37]:
np.round(vec/np.linalg.norm(v), 3)

array([ 0.333, -1.333, -0.333,  0.   , -0.667])

In [ ]:
import numpy as np

In [ ]:
# 5.3

X = [1, 2, 3, 4]
P_X = [0.2, 0.1, 0.4, 0.3]

Y = [-1, 0, 1, 2]
P_Y = [0.5, 0.2, 0.1, 0.2]

def u(x):
    return 3*x + 1
  

def s(y):
    return 5 - y

def mu(rand_var, probs):
    return sum([x*p for x, p in zip(rand_var, probs)])

def var(rand_var, mu, probs):
    return sum([p*(x - mu)**2 for x, p in zip(rand_var, probs)]) 

mu_x = mu(X, P_X)
var_x = var(X, mu_x, P_X)
print('mu X =', mu_x)
print('Var(X) = ', var_x)

mu_y = mu(Y, P_Y)
var_y = var(Y, mu_y, P_Y)
print('mu Y =', mu_y)
print('Var(Y) = ', var_y)

mu_u = mu([u(x) for x in X], P_X)
var_u = var([u(x) for x in X], mu_u, P_X)
print('mu U =', mu_u)
print('Var(U) = ', var_u)

mu_s = mu([s(y) for y in Y], P_Y)
var_s = var([s(y) for y in Y], mu_s, P_Y)
print('mu S =', mu_s)
print('Var(S) = ', var_s)

mu X = 2.8
Var(X) =  1.16
mu Y = 0.0
Var(Y) =  1.4
mu U = 9.4
Var(U) =  10.440000000000001
mu S = 5.0
Var(S) =  1.4


In [ ]:
# var(U-S)

diff = [u(x) - s(y) for x, y in X, Y]


In [ ]:
# Задание 10.1

# Случайный покупатель в книжном магазине купит одну, две или три книги с вероятностью 0.3, 0.4 и 0.3, 
# соответственно. Каждая книга стоит 400 рублей. 
# Найдите математическое ожидание расходов покупателя магазина.

probs = [0.3, 0.4, 0.3]
prices = [1*400, 2*400, 3*400]

sum([p*val for p, val in zip(probs, prices)])

800.0

In [ ]:
X = np.array([2, 3, 4, 5])
P_X = [0.1, 0.2, 0.6, 0.1]

e_x = mu(X, P_X)
e_x

3.7

In [ ]:
mu(X * (X+1), P_X)  # 14.3

18.0

In [ ]:
import numpy as np
import pandas as pd

def cos_sim(v1, v2):
    v1, v2 = np.array(v1), np.array(v2)
    dot_prod = v1.dot(v2)
    prod_lengths = np.sqrt(v1.dot(v1)) * (np.sqrt(v2.dot(v2)))
    return dot_prod/prod_lengths


a = [2, -1, 3]

v1 = [-6, 3, -18]
v2 = [6, -3, 17]
v3 = [0, 0, 1]

for vec in v1, v2, v3:
    print(cos_sim(a, vec))

-0.9600014517991345
0.9651763779473037
0.8017837257372732


In [ ]:
data = np.array( [ [1, 2], [2, 3], [3, 4] ] )

A = pd.DataFrame(data)

A.values


array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
A.values[:, 1]

array([2, 3, 4])

In [ ]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [ ]:
# Задание 10.1

# Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

# В ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую (без пробела):

inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T

inc
# 100,200,100

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [ ]:
# Задание 10.2

# Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

# В ответ запишите диагональные элементы (по побочной диагонали) этой матрицы через запятую (без пробела):
cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T

cons
# 100,80,60

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [ ]:
# Задание 10.3

# Доходы представлены до уплаты налогов. Налоговая ставка - 13%. 
# Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

# Используйте матрицу Inc из предыдущего вопроса, где расходы расположены по столбцам. 
# В ответ запишите элементы из 1 строки этой матрицы через запятую (без пробела):

inc_after_tax = inc - inc*0.13
inc_after_tax
# 87,130.5,78.3

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [ ]:
# Задание 10.4

# Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

# В ответ запишите элементы из 3 строки этой матрицы через запятую (без пробела):

(inc_after_tax - cons)[2]

# 61.8,-26.9,-53

array([ 61.8, -26.9, -53. ])

In [ ]:
inc*cons

array([[ 5000, 15000,  9000],
       [11000, 16000,  1600],
       [ 8400, 18200, 14000]])

In [ ]:
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [ ]:
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [ ]:
np.dot(inc, cons)

array([[17900, 34600, 25600],
       [25800, 49200, 37200],
       [19500, 38400, 30600]])

In [ ]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [ ]:
# Задание 15.1

# Найдите произведение матрицы  и вектора  в том порядке, в котором их можно умножить.

# Координаты вектора введите через запятую (без пробела):
A@x
# 26,30

array([26, 30])

In [ ]:
x.shape

(5,)

In [ ]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [ ]:
# Задание 15.2

# Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

# В ответ запишите элемент из 1 строки и 4 столбца
print(A.shape, B.shape)

(5, 4) (2, 5)


In [ ]:
(B@A)[0,3]

14

In [ ]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [ ]:
# Задание 15.3

# Найдите матрицу Грама системы векторов 
# Введите все элементы этой матрицы через запятую (без пробела), перечисляя построчно:

res = np.array([x, y, z]).T @  np.array([x, y, z])
res

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [ ]:
np.array([x, y, z]) @  np.array([x, y, z]).T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [ ]:
# Подсказка (1 из 1):
A = np.array([x, y, z]).T

A_gram = A.T@A 
print(A_gram)

[[22  3  0]
 [ 3  7  0]
 [ 0  0  3]]


In [ ]:
str_res = ''
for i in A_gram:
  print(i)
  str_res += ','.join([str(v) for v in i])
  str_res += ','

str_res

[22  3  0]
[3 7 0]
[0 0 3]


'22,3,0,3,7,0,0,0,3,'

In [ ]:
A

array([[ 1,  2, -1],
       [ 2,  1,  1],
       [ 1, -1, -1],
       [ 0,  1,  0],
       [ 4,  0,  0]])

In [ ]:
str_res = ''
for i in res:
  print(i)
  str_res += ','.join([str(v) for v in i])
  str_res += ','

str_res

[6 3 0 2 4]
[3 6 0 1 8]
[ 0  0  3 -1  4]
[ 2  1 -1  1  0]
[ 4  8  4  0 16]


'6,3,0,2,4,3,6,0,1,8,0,0,3,-1,4,2,1,-1,1,0,4,8,4,0,16,'

In [ ]:
','.join([ 6,  3,  0,  2,  4])

TypeError: ignored

In [ ]:
# В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

# В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [ ]:
# Задание 15.4

# Найдите вектор выручки Бориса.

# Введите координаты вектора через запятую (без пробела):

counts = Count_DF.values
prices = Price_DF.values

counts

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]])

In [ ]:
np.dot(counts[1], prices[1])

90.1

In [ ]:
counts[1]*prices[1]
3.6,52.5,3,25,6

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [ ]:
# Задание 15.5

# Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

# Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

# Введите координаты вектора через запятую (без пробела):
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
counts * prices

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [ ]:
np.dot((counts * prices), com.T)
# 11.3,15.22,11.9,20.6,41.9,21.2,11.49,38.25

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [ ]:
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [ ]:
# Задание 15.6

# Найдите вектор прибыли стилистов.

# Введите координаты вектора через запятую (без пробела):

res = []
for i in range(counts.shape[0]):
    res.append(np.dot(counts[i], prices[i]))

np.array(res) - np.dot((counts * prices), com.T)
# 50.2,74.88,59.1,67.8,166.6,113.8,66.21,157.75

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [ ]:
# Подсказка (1 из 1):
styl_inc = (prices*counts)@(np.ones(5)-com)

print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [ ]:
np.ones(5)-com

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [ ]:
prices*counts

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [ ]:
import numpy as np


A = np.array([[1, 2], [3, 4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
import numpy as np


A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [ ]:
# Задание 20.1

# Найдите обратную матрицу к матрице А.

# В ответ запишите элемент из 2 строки и 1 столбца, округлив его до трёх знаков после запятой

A_inv = np.linalg.inv(A)

In [ ]:
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [ ]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [ ]:
# Найдите ранг системы векторов v1, v2, v3, v4.

A = np.array([v1, v2, v3, v4])

np.linalg.matrix_rank(A)

4

In [ ]:
res = A @  A.T
res

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [ ]:
np.linalg.det(res)

3716647.9999999995

In [ ]:
# Задание 20.7

# Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.

# В ответ запишите элемент из 3 строки и 1 столбца, округлив его до трёх знаков после запятой

np.linalg.inv(res)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [ ]:
A = np.array([[1, 2], [-3, 1], [1, 2], [1, -1]])

In [ ]:
G = np.dot(A.T, A)
G

array([[12,  0],
       [ 0, 10]])

In [ ]:
G_inv = np.linalg.inv(G)
G_inv

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [ ]:
b = np.array([1, 4, 5, 0])

np.dot(A.T, b)

array([-6, 16])

In [ ]:
np.array

In [ ]:
import numpy as np

In [ ]:
X = np.array([11, 8])

X_st = (X - X.mean())/np.sqrt(sum((X-X.mean())**2))

In [ ]:
X_st
# 0.71,-0.71

array([ 0.70710678, -0.70710678])