In [83]:
import numpy as np

import time

In [94]:
# Входные данные: numpy-массив x размера (n, 2) и два числа p и q (из промежутка [0, 1]).
# Результат: напишите функцию survive_or_not(x, p, q), моделирующую процесс выживания 
# на Титанике, т. е., возвращающую numpy-массив размера (n,), содержащий нули и единицы 
# (1, если человек выжил, 0 в противном случае).

# Sample Input: survive_or_not(np.array([[30, 250], [75, 20]]), 0.5, 0.5)
# Sample Output: np.array([1, 0])

def survive_or_not(x, p, q):
    """# x - numpy array - (m, 2), возраст и цена билета
    изначально вероятность выжить равна 0.7
    если возраст > 60, то вероятность умножается на p (0<p<1)
    если цена < 50, то вероятность умножается на q (0<q<1)"""
    def prob_condit_age(age_price):
        """Return prob conditional on age"""
        age, price = age_price
        prob = 0.7
        if age > 60:
            prob *= p
        if price < 50:
            prob *= q  
        return prob

    start = time.time()
    # probas = np.apply_along_axis(prob_condit_age, 1, x)
    probas = np.array(list(map(prob_condit_age, x)))
    print('time_apply', time.time() - start)
    # print(probas)

    res = np.random.binomial(1, probas)  # prob - numpy-массив с вероятностями выживаемости
    return res

In [66]:
survive_or_not(np.array([[30, 250], [75, 20]]), 0.5, 0.5)

[0.7   0.175]


array([1, 0])

In [164]:
data = np.random.rand(10000000,2)
data[:, 0] = data[:, 0] * 100
data[:, 1] = data[:, 1] * 100

In [98]:
start = time.time()
survive_or_not(data, 0.5, 0.5)
time.time() - start

time_apply 19.09184718132019


19.85110902786255

In [101]:
data = np.array([[30, 250], [75, 20]])

(data[:, 0] > 60) & (data[:, 1] < 50)

array([False,  True])

In [178]:
def survive_or_not(x, p, q):
    """# x - numpy array - (m, 2), возраст и цена билета
    изначально вероятность выжить равна 0.7
    если возраст > 60, то вероятность умножается на p (0<p<1)
    если цена < 50, то вероятность умножается на q (0<q<1)"""

    probas = np.zeros(x.shape[0])
    probas.fill(0.7)
    age_mask = x[:, 0] > 60
    probas[age_mask] *= p
    price_mask = x[:, 1] < 50
    probas[price_mask] *= q

    res = np.random.binomial(1, probas)

    return res


survive_or_not(np.array([[30, 250], [75, 20]]), 0.5, 0.5)

array([1, 0])

In [166]:
data = np.random.rand(10000000,2)
data[:, 0] = data[:, 0] * 100
data[:, 1] = data[:, 1] * 100
data[:4]

array([[85.13334834, 50.1986875 ],
       [85.24311837, 11.62923139],
       [90.7039872 , 57.68720264],
       [32.25734042, 61.41994732]])

In [177]:
start = time.time()
survive_or_not(data, 0.5, 0.5)
time.time() - start

probas shape (10000000,)
age_mask shape (10000000,)


1.1668248176574707

In [2]:
# Входные данные: numpy-массив predictions с вероятностями, numpy-массив answers 
# с ответами на вопрос “Выжил ли пассажир?” (0, если не выжил и 1, если выжил).
# Результат: реализуйте функцию classification_loss(predictions, answers), 
# вычисляющую усреднённую кросс-энтропию между predictions и answers.

# -np.mean(np.log(predictions) * answers + np.log(1 - predictions) * (1 - answers))

# Sample input:classification_loss(np.array([0.2, 0.2]), np.array([1, 0]))
# Sample output: 0.916290731874155
import numpy as np

def classification_loss(predictions, answers):
    """Return Cross Entropy Loss."""
    return -np.mean(np.log(predictions) * answers + np.log(1 - predictions) * (1 - answers))


classification_loss(np.array([0.2, 0.2]), np.array([1, 0]))

0.916290731874155

In [3]:
# Входные данные: numpy-массив predictions (0 или 1), numpy-массив answers (0 или 1).
# Результат: реализуйте функцию accuracy(predictions, answers), вычисляющую долю случаев, 
# когда предсказание совпало с тем, что произошло на самом деле.

# Sample input: accuracy(np.array([1, 0, 1, 1, 0]), np.array([0, 0, 1, 1, 1 ]))
# Sample output: 0.6
import numpy as np


def accuracy(predictions, answers):
    """долю случаев, когда элемент в первом массиве равен соответствующему элементу во втором массиве."""
    return np.mean(predictions == answers)


accuracy(np.array([1, 0, 1, 1, 0]), np.array([0, 0, 1, 1, 1 ]))

0.6

In [33]:
import pandas as pd

df = pd.read_csv('titanic.csv')

df.head()

PassengerId  Survived  Pclass  ... Lifeboat Body  Class
0            1       0.0       3  ...      NaN  NaN    3.0
1            2       1.0       1  ...        4  NaN    1.0
2            3       1.0       3  ...      14?  NaN    3.0
3            4       1.0       1  ...        D  NaN    1.0
4            5       0.0       3  ...      NaN  NaN    3.0

[5 rows x 21 columns]

In [ ]:
# Входные данные: датафрейм data с данными пассажиров Титаника, возраст age.
# Результат: реализуйте функцию survived_ratio(data, age), 
# возвращающую долю выживших пассажиров старше данного возраста age.

# ‘Age’ и ‘Survived

# Sample input: survived_ratio(data, 40)
# Sample output: 0.36666666666666664

In [23]:
# import pandas as pd


def survived_ratio(data, age):
    age_mask = data['Age'] > age
    return data['Survived'][age_mask].mean()


survived_ratio(df, 40)

0.36666666666666664

In [9]:
age_mask = df.loc[:, ['Age']] > 40
df.loc[:, ['Survived']][age_mask]

Survived
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1304       NaN
1305       NaN
1306       NaN
1307       NaN
1308       NaN

[1309 rows x 1 columns]

In [18]:
df['Survived'].mean()

0.3838383838383838

In [14]:
df.shape

(1309, 21)

In [53]:
# Входные данные: Series-объект row с данными пассажира.
# Результат: реализуйте функцию predict(row), возвращающую вероятность - выживет пассажир или нет (число от 0 до 1).

# На вход вашей функции predict(row) будет поступать информация о пассажире.
# Функция должна вернуть вероятность того, что пассажир выжил (число от 0 до 1). 
# Ваша задача - достичь accuracy не менее 75%.

# Например, следующий классификатор имеет accuracy примерно 0.59:

def accuracy(predictions, answers):
    """долю случаев, когда элемент в первом массиве равен соответствующему элементу во втором массиве."""
    return np.mean(predictions == answers)

def predict(row):
  if row['Age'] > 50:
      return 1
  else:
      return 0


surv_age = df[['Survived', 'Age']]  # Class
surv_age.head(2)
surv_age = surv_age.dropna()
surv_age.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    float64
 1   Age       714 non-null    float64
dtypes: float64(2)
memory usage: 16.7 KB


In [ ]:
preds = surv_age.apply(predict, axis=1)
accuracy(np.array(preds), np.array(surv_age['Survived']))

In [68]:
# только по классу 0.6805399325084365
# по классу и полу 0.7165354330708661
# класс, пол, возраст < 60 0.7016806722689075  and row['Age'] < 60
def predict(row):
    if (row['Class'] == 1.0 or row['Class'] == 2.0) and row['Sex'] == 'female':
        return 1
    else:
        return 0


In [69]:
surv_class = df[['Survived', 'Class', 'Sex', 'Age']] 
# surv_class.head(2)
surv_class = surv_class.dropna()
# surv_age.info()
preds = surv_class.apply(predict_by_class, axis=1)
accuracy(np.array(preds), np.array(surv_class['Survived']))

0.7913165266106442

In [ ]:



accuracy(np.array([1, 0, 1, 1, 0]), np.array([0, 0, 1, 1, 1 ]))

def survive_or_not(x, p, q):
    """# x - numpy array - (m, 2), возраст и цена билета
    изначально вероятность выжить равна 0.7
    если возраст > 60, то вероятность умножается на p (0<p<1)
    если цена < 50, то вероятность умножается на q (0<q<1)"""

    probas = np.zeros(x.shape[0])
    probas.fill(0.7)
    age_mask = x[:, 0] > 60
    probas[age_mask] *= p
    price_mask = x[:, 1] < 50
    probas[price_mask] *= q

    res = np.random.binomial(1, probas)

    return res