In [1]:
import numpy as np
import pandas as pd

In [7]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])


In [3]:
share_living_space = apartment[1]/apartment[0]

In [4]:
share_living_space

0.5277310924369748

In [8]:
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)

apartment.ndim

1

In [9]:
len(apartment)

5

In [11]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

t.mean()

21.25

In [13]:
np.array([120, 150, 90]) + np.array([130, 130, 130]) + np.array([2,3,2.5])*72

array([394., 496., 400.])

In [14]:
-200*np.array([3,4,5,9]) + 400*np.array([1, 5, 3, 6])

array([-200, 1200,  200,  600])

In [15]:
a = np.array([4,6,1])

np.sqrt(np.dot(a, a))

7.280109889280518

In [2]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [5]:
Hut_Paradise_DF.loc[4]

1.Rent              40
2.Area              33
3.Rooms              1
4.Floor              6
5.Demo two weeks    20
6.Liv.Area          16
Name: 4, dtype: int64

In [6]:
Hut_Paradise_DF.loc[4].values

array([40, 33,  1,  6, 20, 16])

In [8]:
Hut_Paradise_DF['4.Floor'].values

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [10]:
Hut_Paradise_DF['4.Floor'][2]

10

In [11]:
Hut_Paradise_DF.shape

(9, 6)

In [13]:
(Hut_Paradise_DF['2.Area'] - Hut_Paradise_DF['6.Liv.Area']).values

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [15]:
(Hut_Paradise_DF['1.Rent'] * 0.4).values

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [16]:
min_demo = np.array([10,20,30,15,5,40,20,8,20])

Hut_Paradise_DF['5.Demo two weeks'] @ min_demo

1348

In [17]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [20]:
av_bw = 2*v + -3*w
av_bw

array([-3, 14,  3,  4,  2])

In [21]:
u @ av_bw

0

In [34]:
for vec in u, v, w:
  print(np.round(vec/np.linalg.norm(vec), 3))

[0.866 0.    0.289 0.289 0.289]
[ 0.     0.333  0.     0.667 -0.667]
[ 0.213 -0.853 -0.213  0.    -0.426]


In [37]:
np.round(vec/np.linalg.norm(v), 3)

array([ 0.333, -1.333, -0.333,  0.   , -0.667])