# Матрицы и векторы

In [1]:
import numpy as np

## 1. Скалярное умножение векторов

$$(a, b) = \sum a_i b_i$$

In [2]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

In [3]:
a

array([1, 2, 3])

In [4]:
np.dot(a, b)

26

Реализуем скалярное произведение средствами Python

In [5]:
sum([x * y for x, y in zip(a, b)])

26

Примеры:

Следующие два примера – ортогональные векторы

In [6]:
np.dot([0, 1], [1, 0])

0

In [7]:
np.dot([3, 1, 2], [-1, 1, 1])

0

In [8]:
np.dot([1, 2, 3], [2, 4, 6])

28

In [9]:
np.dot([-10, -1], [1, 1])

-11

## 2. Длина вектора через скалярное произведение

$$\lvert a\lvert= \sqrt{(a, a)}$$

In [10]:
a

array([1, 2, 3])

In [11]:
np.sqrt(np.dot(a, a))

3.7416573867739413

In [12]:
np.linalg.norm(a)

3.7416573867739413

In [13]:
np.linalg.norm([0, 1])

1.0

In [14]:
np.linalg.norm([3, 4])

5.0

In [15]:
np.linalg.norm([-1, -1])

1.4142135623730951

In [16]:
np.sqrt(2)

1.4142135623730951

## 3. Сложение матриц и умножение на число

Матрицы складываются поэлементно. При умножении на число все элементы матрицы умножаются на это число.

In [17]:
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 2))

In [18]:
a, b

(array([[7, 0],
        [1, 8]]), array([[7, 9],
        [1, 0]]))

In [19]:
a + b

array([[14,  9],
       [ 2,  8]])

In [20]:
a

array([[7, 0],
       [1, 8]])

In [21]:
a * 2

array([[14,  0],
       [ 2, 16]])

$I$ или $E$ – единичная матрица

In [22]:
eye_matrix = np.eye(3)

In [23]:
eye_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
eye_matrix * 5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

## 4. Умножение матриц

Для умножения нужно, чтобы **средние** размерности совпадали: умножить можно только $n*k$ на $k*m$  
Под средними размерностями подразумеваются те размерности, которые находятся посередине при записи размерностей двух матриц. В примере выше это *k*

In [25]:
a

array([[7, 0],
       [1, 8]])

In [26]:
b

array([[7, 9],
       [1, 0]])

Проверим на первой строке первой матрицы и на первом столбце второй матрицы  
**1, 1** – первая строка первой матрицы, первый столбец второй матрицы  
([5 7], [1 2]) – скалярное произведение этих векторов

5\*1 + 7\*2 = 19


**1, 2**  
([5, 7], [2, 6])  
5\*2 + 7\*6 = 52

In [27]:
np.dot(a, b)

array([[49, 63],
       [15,  9]])

In [28]:
a @ b

array([[49, 63],
       [15,  9]])

In [29]:
np.matmul(a, b)

array([[49, 63],
       [15,  9]])

dot и matmul работают одинаково для 2д матриц, но matmul не позволяет перемножать скаляры и работает по-другому для измерений 3+

In [30]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (5, 3))

In [31]:
a, b

(array([[1, 1, 4, 3, 4],
        [4, 3, 0, 1, 2]]), array([[4, 4, 0],
        [2, 2, 2],
        [2, 0, 3],
        [4, 1, 0],
        [2, 1, 3]]))

In [32]:
result = np.matmul(a, b)

In [33]:
result

array([[34, 13, 26],
       [30, 25, 12]])

Размерность:

In [34]:
result.shape

(2, 3)

## 5. Связь со скалярным произведением

In [35]:
result

array([[34, 13, 26],
       [30, 25, 12]])

In [36]:
# i = 1, j = 2
result[1, 2]

12

In [37]:
a, b

(array([[1, 1, 4, 3, 4],
        [4, 3, 0, 1, 2]]), array([[4, 4, 0],
        [2, 2, 2],
        [2, 0, 3],
        [4, 1, 0],
        [2, 1, 3]]))

In [38]:
np.dot(a[1,:], b[:, 2])

12

В результате умножения матриц в элементе с индексом (i, j) лежит скалярное произведение i-й строки первой матрицы на j-й столбец второй матрицы

## 6. Умножение матриц некоммутативно

Если средние размерности не совпадают, то умножить вообще нельзя:

Перемножение скаляров коммутативно:

In [39]:
2 * 3 == 3 * 2

True

In [40]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (4, 3))
# np.dot(a, b)

Средние размерности совпадают, но размерности матриц разные:

In [41]:
a = np.random.randint(0, 5, (2, 5))
b = np.random.randint(0, 5, (5, 3))

In [42]:
# np.dot(a, b)

In [43]:
# np.dot(b, a)

Размерности матриц одинаковые:

In [44]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))

In [45]:
a, b

(array([[2, 2],
        [4, 4]]), array([[4, 0],
        [0, 4]]))

In [46]:
np.dot(a, b)

array([[ 8,  8],
       [16, 16]])

In [47]:
np.dot(b, a)

array([[ 8,  8],
       [16, 16]])

## 7. Умножение матриц ассоциативно

$$(AxB)xC==Ax(BxC)$$

In [48]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))
c = np.random.randint(0, 5, (2, 2))

In [49]:
np.dot(np.dot(a, b), c) == np.dot(a, np.dot(b, c))

array([[ True,  True],
       [ True,  True]])

## 8. Вычисление определителей

In [50]:
a = np.random.randint(0, 5, (2, 2))
a

array([[3, 4],
       [0, 3]])

In [51]:
det = a[0, 0]*a[1, 1] - a[1, 0]*a[0, 1]
det

9

In [52]:
np.linalg.det(a)

9.000000000000002

Примеры:

In [53]:
# Вторая строка равна первой, умноженной на 2 – строки линейно зависимы
np.linalg.det(np.array([[1, 2], [2, 4]]))

0.0

In [54]:
# Диагональная матрица, поэтому произведение элементов на диагонали
np.linalg.det(np.array([[2, 0], [0, 3]]))

6.0

In [55]:
np.array([[2, 2], [0, 3]])

array([[2, 2],
       [0, 3]])

In [56]:
# Верхнетреугольная матрица, поэтому произведение элементов на диагонали
np.linalg.det(np.array([[2, 2], [0, 3]]))

6.0

## 9. Определитель произведения матриц

$$det(A*B)=det(A)*det(B)$$

In [57]:
a = np.random.randint(0, 5, (2, 2))
b = np.random.randint(0, 5, (2, 2))

In [58]:
a, b

(array([[3, 1],
        [1, 0]]), array([[2, 0],
        [4, 2]]))

In [59]:
np.linalg.det(np.dot(a, b))

-4.000000000000001

In [60]:
np.linalg.det(a) * np.linalg.det(b)

-4.0

## 10. Единичная и обратная матрицы

Вычисления работают для квадратных матриц. Если определитель равен 0, обратной матрицы не существует.

$$A \cdot A^{-1} = E$$

In [61]:
a

array([[3, 1],
       [1, 0]])

In [62]:
np.linalg.det(a)

-1.0

In [63]:
np.linalg.inv(a)

array([[ 0.,  1.],
       [ 1., -3.]])

In [64]:
np.dot(np.linalg.inv(a), a)

array([[1., 0.],
       [0., 1.]])

In [65]:
np.linalg.det(np.array([[1, 2], [2, 4]]))

0.0

In [66]:
# np.linalg.inv(np.array([[1, 2], [2, 4]]))
# LinAlgError: Singular matrix

## 11. Коммутативность прямой и обратной матрицы

$$A \cdot A^{-1} = A^{-1} \cdot A  = E$$

In [67]:
a

array([[3, 1],
       [1, 0]])

In [68]:
inv_a = np.linalg.inv(a)

In [69]:
inv_a

array([[ 0.,  1.],
       [ 1., -3.]])

In [70]:
np.dot(a, inv_a).astype(int)

array([[1, 0],
       [0, 1]])

In [71]:
np.dot(inv_a, a)

array([[1., 0.],
       [0., 1.]])

## 12. Поиск обратной матрицы методом Крамера

In [72]:
def matrix_inverse(m):
    # только 2D
    determinant = np.linalg.det(m)
    return [[m[1][1]/determinant, -1*m[0][1]/determinant],
            [-1*m[1][0]/determinant, m[0][0]/determinant]]

In [73]:
a

array([[3, 1],
       [1, 0]])

In [74]:
np.linalg.inv(a)

array([[ 0.,  1.],
       [ 1., -3.]])

In [75]:
np.array(matrix_inverse(a))

array([[-0.,  1.],
       [ 1., -3.]])

## 13. Тензорное произведение векторов

Как работает:

$$a = 
\begin{pmatrix}
a_1 & a_2
\end{pmatrix}$$

$$b = 
\begin{pmatrix}
b_1 & b_2
\end{pmatrix}$$

$$
c = a \space tensordot \space b = 
\begin{pmatrix}
a_1 \cdot [b_1, b_2] \\
a_2 \cdot [b_1, b_2] \\
\end{pmatrix}
$$

In [76]:
a = np.random.randint(0, 10, size=2)
b = np.random.randint(0, 10, size=2)

In [77]:
a, b

(array([8, 5]), array([2, 2]))

In [78]:
np.tensordot(a, b, axes=0)

array([[16, 16],
       [10, 10]])

Ссылка: https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

Посмотрим как делать slice в тензоре

In [79]:
test = np.random.randint(0, 10, size=(2, 2, 3))

In [80]:
test

array([[[8, 3, 9],
        [0, 9, 9]],

       [[5, 7, 8],
        [4, 7, 9]]])

In [81]:
test[:, :, 1]

array([[3, 9],
       [7, 7]])